name: dart_discord_rpc_ffi
description: FFI & NativePorts interface to Discord RPC.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
